BEGIN TRANSACTION;

DROP TABLE IF EXISTS Portfolio;

DROP TABLE IF EXISTS Orderbook;

DROP TABLE IF EXISTS stockexchange;

DROP TABLE IF EXISTS company;

DROP TABLE IF EXISTS BrokerT;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS Broker_details;

DROP TABLE IF EXISTS Transactions;


END TRANSACTION;
